TravelistaBlogProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from TravelistaBlogProject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path
from .views import *

app_name = 'account'
urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
]

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('', index, name='index'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', about, name='about'),
    path('blog/list/', BlogListView.as_view(), name='blog_list'),
    path('blog/search/', BlogListView.as_view(), name='blog_search'),
    path('blog/author/<str:author>/', BlogListView.as_view(), name='blog_author'),
    path('blog/tag/<str:tag>/', BlogListView.as_view(), name='blog_tag'),
    path('blog/category/<str:category>/', BlogListView.as_view(), name='blog_category'),
    path('blog/detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
]

templates/base/footer.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<!-- start footer Area -->
<footer class="footer-area section-gap">
    <div class="container">

        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Agency</h6>
                    <p>
                        The world has become so fast paced that people don’t want to stand by reading a page of
                        information, they would much rather look at a presentation and understand the message. It has
                        come to a point
                    </p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Navigation Links</h6>
                    <div class="row">
                        <div class="col">
                            <ul>
                                <li><a href="#">Home</a></li>
                                <li><a href="#">Feature</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Portfolio</a></li>
                            </ul>
                        </div>
                        <div class="col">
                            <ul>
                                <li><a href="#">Team</a></li>
                                <li><a href="#">Pricing</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p>
                        For business professionals caught between high OEM price and mediocre print and graphic output.
                    </p>
                    <div id="mc_embed_signup">
                        <form target="_blank"
                              action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                              method="get" class="subscription relative">
                            <div class="input-group d-flex flex-row">
                                <label>
                                    <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''"
                                           onblur="this.placeholder = 'Email Address '" required="" type="email">
                                </label>
                                <button class="btn bb-btn"><span class="lnr lnr-location"></span></button>
                            </div>
                            <div class="mt-10 info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">InstaFeed</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><img src="{% static "statics/img/i1.jpg" %}" alt=""></li>
                        <li><img src="{% static "statics/img/i2.jpg" %}" alt=""></li>
                        <li><img src="{% static "statics/img/i3.jpg" %}" alt=""></li>
                        <li><img src="{% static "statics/img/i4.jpg" %}" alt=""></li>
                        <li><img src="{% static "statics/img/i5.jpg" %}" alt=""></li>
                        <li><img src="{% static "statics/img/i6.jpg" %}" alt=""></li>
                        <li><img src="{% static "statics/img/i7.jpg" %}" alt=""></li>
                        <li><img src="{% static "statics/img/i8.jpg" %}" alt=""></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row footer-bottom d-flex justify-content-between align-items-center">
            <p class="col-lg-8 col-sm-12 footer-text m-0">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                    href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            <div class="col-lg-4 col-sm-12 footer-social">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
            </div>
        </div>
    </div>
</footer>
<!-- End footer Area -->
</body>
</html>

templates/base/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Travelista</title>
    <style>
        /* استایل مشترک برای همه لینک‌ها و دکمه‌ها */
        .auth-links {
            list-style: none;
            padding: 0;
            margin: 0;
            display: flex;
            gap: 15px;
            align-items: center;
        }
        
        .auth-link {
            color: white;
            text-decoration: none;
            font-size: 14px;
            padding: 5px 10px;
            border-radius: 4px;
            transition: background-color 0.2s;
        }
        
        .auth-link:hover {
            background-color: rgba(255, 255, 255, 0.1);
        }
        
        /* استایل دکمه Logout که شبیه لینک نمایش داده می‌شود */
        .logout-btn {
            background: none;
            border: none;
            color: white;
            cursor: pointer;
            font: inherit;
            padding: 5px 10px;
            margin: 0;
        }
        
        /* استایل نام کاربری */
        .username {
            color: white;
            font-weight: 500;
            padding: 5px 10px;
        }
    </style>
</head>
<body>
    <header id="header">
        <div class="header-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-sm-6 col-6 header-top-left">
                        <ul class="auth-links">
                            {% if request.user.is_authenticated %}
                                <li><span class="username">{{ request.user.username }}</span></li>
                                <li>
                                    <form action="{% url 'account:logout' %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="auth-link logout-btn">
                                            Logout
                                        </button>
                                    </form>
                                </li>
                            {% else %}
                                <li><a href="{% url 'account:register' %}" class="auth-link">Register</a></li>
                                <li><a href="{% url 'account:login' %}" class="auth-link">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="container main-menu">
            <div class="row align-items-center justify-content-between d-flex">
                <div id="logo">
                    <a href="{% url 'blog:index' %}">
                        <img src="{% static 'statics/img/logo.png' %}" alt="Travelista Logo">
                    </a>
                </div>
                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        <li><a href="{% url 'blog:index' %}">Home</a></li>
                        <li><a href="{% url 'blog:about' %}">About</a></li>
                        <li class="menu-has-children"><a href="{% url 'blog:blog_list' %}">Blog</a></li>
                        <li><a href="{% url 'blog:contact' %}">Contact</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
</body>
</html>

templates/base/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static "statics/img/fav.png" %}">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Travel</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="{% static "statics/css/linearicons.css" %}">
    <link rel="stylesheet" href="{% static "statics/css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "statics/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "statics/css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "statics/css/jquery-ui.css" %}">
    <link rel="stylesheet" href="{% static "statics/css/nice-select.css" %}">
    <link rel="stylesheet" href="{% static "statics/css/animate.min.css" %}">
    <link rel="stylesheet" href="{% static "statics/css/owl.carousel.css" %}">
    <link rel="stylesheet" href="{% static "statics/css/main.css" %}">
</head>
<body>
{% include "base/header.html" %}

{% block content %}
	
{% endblock content %}

{% include "base/footer.html" %}
{% include "base/scripts.html" %}


</body>
</html>

templates/base/scripts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script src="{% static "statics/js/vendor/jquery-2.2.4.min.js" %}"></script>
<script src="{% static "statics/js/popper.min.js" %}"></script>
<script src="{% static "statics/js/vendor/bootstrap.min.js" %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{% static "statics/js/jquery-ui.js" %}"></script>
<script src="{% static "statics/js/easing.min.js" %}"></script>
<script src="{% static "statics/js/hoverIntent.js" %}"></script>
<script src="{% static "statics/js/superfish.min.js" %}"></script>
<script src="{% static "statics/js/jquery.ajaxchimp.min.js" %}"></script>
<script src="{% static "statics/js/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "statics/js/jquery.nice-select.min.js" %}"></script>
<script src="{% static "statics/js/owl.carousel.min.js" %}"></script>
<script src="{% static "statics/js/mail-script.js" %}"></script>
<script src="{% static "statics/js/main.js" %}"></script>
</body>
</html>