TravelistaBlogProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from TravelistaBlogProject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('', index, name='index'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', about, name='about'),
    path('blog/list/', BlogListView.as_view(), name='blog_list'),
    path('blog/search/', BlogListView.as_view(), name='blog_search'),
    path('blog/author/<str:author>/', BlogListView.as_view(), name='blog_author'),
    path('blog/tag/<str:tag>/', BlogListView.as_view(), name='blog_tag'),
    path('blog/category/<str:category>/', BlogListView.as_view(), name='blog_category'),
    path('blog/detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
]

blog/models.py
from django.contrib.auth import get_user_model
from account.models import *
from django.db import models


# Create your models here.

class Tag(models.Model):
    tag_name = models.CharField(max_length=120)

    def __str__(self):
        return self.tag_name


class Category(models.Model):
    category_name = models.CharField(max_length=255)

    def __str__(self):
        return self.category_name


class Post(models.Model):
    post_image = models.ImageField(upload_to='post_images', null=True, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField(Category)
    tags = models.ManyToManyField(Tag)
    post_status = models.BooleanField(default=False)
    post_views = models.IntegerField(default=0)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.subject

blog/forms.py
from django import forms

from blog.models import Contact


class ContactForm(forms.Form):
    name = forms.CharField(max_length=120, label='Name')
    email = forms.EmailField(label='Email')
    subject = forms.CharField(max_length=120, label='Subject')
    message = forms.CharField(widget=forms.Textarea, label='Message')

blog/views.py
from django.db.models import Count
from django.shortcuts import render
from django.views.generic import *
from .forms import ContactForm
from blog.models import *


#

# Create your views here.

def index(request):
    return render(request, "landing_page/landing_page.html")


def about(request):
    return render(request, "landing_page/about.html")


class BlogListView(ListView):
    model = Post
    template_name = "blog/blog-list.html"
    context_object_name = "posts"
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.annotate(post_count=Count('post')).filter(post_count__gt=0)
        context['recent_posts'] = Post.objects.filter(post_status=True).order_by('-created_at')[:3]
        context['tags'] = Tag.objects.all()
        return context

    def get_queryset(self):
        queryset = super().get_queryset().filter(post_status=True)

        search_query = self.request.GET.get('search')
        if search_query:
            queryset = queryset.filter(title__icontains=search_query)

        category = self.kwargs.get("category")
        if category:
            queryset = queryset.filter(category__category_name=category)

        author = self.kwargs.get("author")
        if author:
            queryset = queryset.filter(author__user__username=author)

        tag = self.kwargs.get("tag")
        if tag:
            queryset = queryset.filter(tags__tag_name=tag)

        return queryset.order_by('-created_at')


class BlogDetailView(DetailView):
    model = Post
    template_name = "blog/blog-single.html"
    context_object_name = "post"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        obj.post_views += 1
        obj.save()
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.annotate(post_count=Count('post')).filter(post_count__gt=0)
        context['tags'] = Tag.objects.all()
        return context


class ContactView(FormView):
    template_name = "landing_page/contact.html"
    form_class = ContactForm
    success_url = "/contact/"

    def form_valid(self, form):
        Contact.objects.create(
            name=form.cleaned_data['name'],
            email=form.cleaned_data['email'],
            subject=form.cleaned_data['subject'],
            message=form.cleaned_data['message']
        )
        return super().form_valid(form)


class SearchView(ListView):
    model = Post
    queryset = Post.objects.filter(title__icontains='title')
    template_name = "blog/blog_search_widget.html"

templates/blog/blog-list.html
{% extends "base/main.html" %}
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<body>
{% block content %}
    <!-- start banner Area -->
    <section class="banner-area relative blog-home-banner" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content blog-header-content col-lg-12">
                    <h1 class="text-white">
                        Dude You’re Getting
                        a Telescope
                    </h1>
                    <p class="text-white">
                        There is a moment in the life of any aspiring astronomer that it is time to buy that first
                    </p>

                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

    {% include "blog/blog_category_widgets.html" %}


    <!-- Start post-content Area -->
    <section class="post-content-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    {% for post in posts %}
                        <div class="single-post row">
                            <div class="col-lg-3  col-md-3 meta-details">
                                <ul class="tags">
                                    {% for tag in post.tags.all %}
                                        <li>
                                            <a href="{% url 'blog:blog_tag' tag=tag.tag_name %}">{{ tag.tag_name }}</a>
                                            {% if not forloop.last %}, {% endif %}
                                        </li>
                                    {% empty %}
                                        <li>No Tags</li>
                                    {% endfor %}
                                </ul>
                                <div class="user-details row">
                                    <p class="user-name col-lg-12 col-md-12 col-6"><a
                                            href="{% url 'blog:blog_author' author=post.author.user %}">{{ post.author.user.username }}
                                    </a> <span
                                            class="lnr lnr-user"></span></p>
                                    <p class="date col-lg-12 col-md-12 col-6"><a href="#">
                                        {{ post.created_at | date:"d M Y" }}</a> <span
                                            class="lnr lnr-calendar-full"></span></p>
                                    <p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.post_views }}
                                        Views</a> <span
                                            class="lnr lnr-eye"></span></p>
                                </div>
                            </div>
                            <div class="col-lg-9 col-md-9 ">
                                <div class="feature-img">
                                    <img class="img-fluid"
                                         src="{% static "statics/img/blog/feature-img1.jpg" %}"
                                         alt="">
                                </div>
                                <a class="posts-title" href="{% url 'blog:blog_detail' pk=post.pk %}">
                                    <h3>
                                        {{ post.title }}
                                    </h3>
                                </a>
                                <p class="excert">
                                    {{ post.content }}
                                </p>
                                <a href="{% url 'blog:blog_detail' pk=post.pk %}" class="primary-btn">View More</a>
                            </div>
                        </div>
                    {% endfor %}
                    {% if is_paginated %}
                        <nav class="blog-pagination justify-content-center d-flex">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page=
                                                {{ page_obj.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}"
                                           class="page-link" aria-label="Previous">
                        <span aria-hidden="true">
                            <span class="lnr lnr-chevron-left"></span>
                        </span>
                                        </a>
                                    </li>
                                {% endif %}

                                {% for num in page_obj.paginator.page_range %}
                                    {% if page_obj.number == num %}
                                        <li class="page-item active"><a href="#" class="page-link">{{ num }}</a></li>
                                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                        <li class="page-item">
                                            <a href="?page=
                                                    {{ num }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}"
                                               class="page-link">{{ num }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}

                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page=
                                                {{ page_obj.next_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}"
                                           class="page-link" aria-label="Next">
                        <span aria-hidden="true">
                            <span class="lnr lnr-chevron-right"></span>
                        </span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                </div>
                <div class="col-lg-4 sidebar-widgets">
                    <div class="widget-wrap">
                        {% include "blog/blog_search_widget.html" %}
                        {% include "blog/blog_recent_posts_widget.html" %}
                        {% include "blog/blog_ads_widget.html" %}
                        {% include "blog/blog_post_category_widget.html" %}
                        {% include "blog/blog_tag_cloud_widget.html" %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End post-content Area -->
{% endblock %}
</body>
</html>

templates/blog/blog-single.html
{% extends "base/main.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<body>

{% block content %}

    <!-- start banner Area -->
    <section class="relative about-banner">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                        {{ post.title }}
                    </h1>
                    <p class="text-white link-nav"><a href="{% url 'blog:index' %}">Home </a> <span
                            class="lnr lnr-arrow-right"></span><a href="{% url 'blog:blog_list' %}">Blog </a>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

    <!-- Start post-content Area -->
    <section class="post-content-area single-post-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    <div class="single-post row">
                        <div class="col-lg-12">
                            <div class="feature-img">
                                <img class="img-fluid" src="{% static "statics/img/blog/feature-img1.jpg" %}" alt="">
                            </div>
                        </div>
                        <div class="col-lg-3  col-md-3 meta-details">
                            <ul class="tags">
                                {% for tag in post.tags.all %}
                                    <li>
                                        <a href="{% url 'blog:blog_tag' tag=tag.tag_name %}">{{ tag.tag_name }}</a>
                                        {% if not forloop.last %}, {% endif %}
                                    </li>
                                {% empty %}
                                    <li>No Tags</li>
                                {% endfor %}
                            </ul>
                            <div class="user-details row">
                                <p class="user-name col-lg-12 col-md-12 col-6"><a
                                        href="{% url "blog:blog_author" author=post.author.user %}">{{ post.author.user.username }}</a>
                                    <span
                                            class="lnr lnr-user"></span></p>
                                <p class="date col-lg-12 col-md-12 col-6"><a
                                        href="#">{{ post.created_at | date:"d M Y" }}</a> <span
                                        class="lnr lnr-calendar-full"></span></p>
                                <p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.post_views }} Views</a>
                                    <span
                                            class="lnr lnr-eye"></span></p>
                            </div>
                        </div>
                        <div class="col-lg-9 col-md-9">
                            <h3 class="mt-20 mb-20">{{ post.title }}</h3>
                            <p class="excert">
                                {{ post.content }}
                            </p>
                        </div>

                    </div>
                    <div class="comments-area">
                        <h4>05 Comments</h4>
                        <div class="comment-list">
                            <div class="single-comment justify-content-between d-flex">
                                <div class="user justify-content-between d-flex">
                                    <div class="thumb">
                                        <img src="{% static "statics/img/blog/c1.jpg" %}" alt="">
                                    </div>
                                    <div class="desc">
                                        <h5><a href="#">Emilly Blunt</a></h5>
                                        <p class="date">December 4, 2017 at 3:12 pm </p>
                                        <p class="comment">
                                            Never say goodbye till the end comes!
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="comment-form">
                        <h4>Leave a Comment</h4>
                        <form>
                            <div class="form-group form-inline">
                                <div class="form-group col-lg-6 col-md-12 name">
                                    <input type="text" class="form-control" id="name" placeholder="Enter Name"
                                           onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
                                </div>
                                <div class="form-group col-lg-6 col-md-12 email">
                                    <input type="email" class="form-control" id="email"
                                           placeholder="Enter email address"
                                           onfocus="this.placeholder = ''"
                                           onblur="this.placeholder = 'Enter email address'">
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" id="subject" placeholder="Subject"
                                       onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
                            </div>
                            <div class="form-group">
                            <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
                                      onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
                                      required=""></textarea>
                            </div>
                            <a href="#" class="primary-btn text-uppercase">Post Comment</a>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4 sidebar-widgets">
                    <div class="widget-wrap">
                        {% include "blog/blog_user_info_widget.html" %}
                        {% include "blog/blog_ads_widget.html" %}
                        {% include "blog/blog_post_category_widget.html" %}
                        {% include "blog/blog_tag_cloud_widget.html" %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End post-content Area -->
{% endblock %}


</body>
</html>
{##}

templates/blog/blog_ads_widget.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{% static "statics/img/blog/ads-banner.jpg" %}" alt=""></a>
</div>
</body>
</html>

templates/blog/blog_category_widgets.html
{% load static %}
{#It's for header before post list show (food, politic, ...) #}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90 ">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="single-cat-widget">
                    <div class="content relative">
                        <div class="overlay overlay-bg"></div>
                        <a href="#" target="_blank">
                            <div class="thumb">
                                <img class="content-image img-fluid d-block mx-auto" src="{% static "statics/img/blog/cat-widget1.jpg" %}"
                                     alt="">
                            </div>
                            <div class="content-details">
                                <h4 class="content-title mx-auto text-uppercase">Social life</h4>
                                <span></span>
                                <p>Enjoy your social life together</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="single-cat-widget">
                    <div class="content relative">
                        <div class="overlay overlay-bg"></div>
                        <a href="#" target="_blank">
                            <div class="thumb">
                                <img class="content-image img-fluid d-block mx-auto" src="{% static "statics/img/blog/cat-widget2.jpg" %}"
                                     alt="">
                            </div>
                            <div class="content-details">
                                <h4 class="content-title mx-auto text-uppercase">Politics</h4>
                                <span></span>
                                <p>Be a part of politics</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="single-cat-widget">
                    <div class="content relative">
                        <div class="overlay overlay-bg"></div>
                        <a href="#" target="_blank">
                            <div class="thumb">
                                <img class="content-image img-fluid d-block mx-auto" src="{% static "statics/img/blog/cat-widget3.jpg" %}"
                                     alt="">
                            </div>
                            <div class="content-details">
                                <h4 class="content-title mx-auto text-uppercase">Food</h4>
                                <span></span>
                                <p>Let the food be finished</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End top-category-widget Area -->

</body>
</html>

templates/blog/blog_post_category_widget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for cat in categories %}
            <li>
                <a href="{% url 'blog:blog_category' category=cat.category_name  %}" class="d-flex justify-content-between">
                    <p>{{ cat }}</p>
                    <p>{{ cat.post_count }}</p>
                </a>
            </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

templates/blog/blog_recent_posts_widget.html
{% load static %}
{% load humanize %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Recent Posts</h4>
    {% for post in posts %}
    	<div class="popular-post-list">
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src="{% static "statics/img/blog/pp1.jpg" %}" alt="">
            </div>
            <div class="details">
                <a href="{% url 'blog:blog_detail' pk=post.pk %}"><h6>{{ post }}</h6></a>
                <p>{{ post.created_at | naturaltime }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
    
    
</div>
</body>
</html>

templates/blog/blog_search_widget.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:blog_search' %}" method="get">
        <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''"
               onblur="this.placeholder = 'Search Posts'">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>
</body>
</html>

templates/blog/blog_tag_cloud_widget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
        {% for tag in tags %}
        	<li><a href="{% url 'blog:blog_tag' tag=tag.tag_name %}">{{ tag }}</a></li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

templates/blog/blog_user_info_widget.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="single-sidebar-widget user-info-widget">
    <img src="{% static "statics/img/blog/user-info.png" %}" alt="">
    <a href="{% url 'blog:blog_author' author=post.author.user %}"><h4>{{ post.author.user.username }}</h4></a>
    <p>
        Senior blog writer
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-telegram"></i></a></li>
    </ul>
    <p>
        {{ post.author.bio }}
    </p>
</div>
</body>
</html>